version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_batch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "admin1234567890@"
      POSTGRES_DB: diabetesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # (optional) auto-create table on first run by dropping an init.sql next to this compose file
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_batch
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch_batch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana_batch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  nifi:
    image: apache/nifi:1.23.2
    container_name: nifi_batch
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_ZK_CONNECT_STRING=
      - NIFI_ELECTION_MAX_WAIT=30 sec
      - NIFI_SENSITIVE_PROPS_KEY=12345678901234567890A
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      - NIFI_JVM_HEAP_INIT=1g
      - NIFI_JVM_HEAP_MAX=1g
    volumes:
      # keep logs & conf persisted
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_conf:/opt/nifi/nifi-current/conf
      # data mounts
      - ./input:/data/input
      - ./output:/data/output
      - ./cleaned_output:/data/cleaned_output
      # drivers mount - only mount to drivers, not lib to avoid conflicts
      - ./drivers:/opt/nifi/nifi-current/drivers
    networks:
      - app-network
    restart: "no"
    mem_limit: 3g
    depends_on:
      - postgres
      - elasticsearch

volumes:
  postgres_data:
  nifi_logs:
  nifi_conf:
  elasticsearch_data:

networks:
  app-network:
    driver: bridge